[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "django>=6.1.1",
    "djangorestframework>=3.18.0",
    "google-genai>=2.20.0",
    "groq>=1.7.0",
    "langchain>=1.4.0",
]

[dependency-groups]
dev = [
    "bandit>=1.9.4",
    "django-debug-toolbar>=8.0.0",
    "mypy>=2.3.1",
    "pylint>=4.0.7",
    "pytest>=9.1.1",
    "pytest-cov>=7.1.0",
    "radon>=6.0.1",
    "ruff>=0.16.5",
]
